version: "3.8"

services:
  harena-dbms:
    container_name: harena-dbms
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: harena
      POSTGRES_USER: harenauser
      POSTGRES_PASSWORD: harenapassword
    volumes:
      - ./data/pgsql/harena:/var/lib/postgresql/data
      - ./data/pgsql/harena-impexp:/docker-entrypoint-initdb.d
    networks:
      - harena

networks:
  harena:
    driver: bridge


