# Generated by Django 5.1.7 on 2025-06-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorinvitetoken',
            name='used_by',
        ),
        migrations.AddField(
            model_name='professorinvitetoken',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professorinvitetoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
