# Generated by Django 5.1.7 on 2025-06-06 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='harena.institution'),
        ),
        migrations.CreateModel(
            name='InstitutionDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='harena.institution')),
            ],
        ),
    ]
