# Generated by Django 5.1.7 on 2025-06-24 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harena', '0002_remove_professorinvitetoken_used_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('variant', models.CharField(choices=[('viewer_existing', 'Viewer (Existing User)'), ('author_existing', 'Author (Existing User)'), ('viewer_guest', 'Viewer (Guest - Not Registered)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used_once', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='harena.quest')),
                ('used_by', models.ManyToManyField(blank=True, to='harena.person')),
            ],
        ),
    ]
