# Generated by Django 5.1.7 on 2025-06-10 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harena', '0002_institution_person_institution_institutiondomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='ProfessorInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harena.institution')),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_invite_tokens', to='harena.person')),
            ],
        ),
    ]
