# Generated by Django 5.1.7 on 2025-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harena', '0003_questaccesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questaccesstoken',
            name='is_used_once',
        ),
        migrations.RemoveField(
            model_name='questaccesstoken',
            name='variant',
        ),
        migrations.AddField(
            model_name='questaccesstoken',
            name='group',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('author', 'Author'), ('editor', 'Editor')], default='viewer', max_length=20),
        ),
        migrations.AddField(
            model_name='questaccesstoken',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questaccesstoken',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('student', 'Student'), ('professor', 'Professor')], default='guest', max_length=20),
        ),
    ]
