# Generated by Django 5.1.7 on 2025-06-17 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harena', '0004_quest_questviewerinvitetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('possible_answers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complexity', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('postgraduate', 'Postgraduate')], default='undergraduate', max_length=30)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_images/')),
                ('case_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_owned', to='harena.person')),
            ],
        ),
        migrations.CreateModel(
            name='QuestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_cases', to='harena.case')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_cases', to='harena.quest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quest', 'case'), name='unique_quest_case')],
            },
        ),
    ]
