# Generated by Django 5.1.7 on 2025-06-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harena', '0005_case_questcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='active_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
