# Generated by Django 5.1.7 on 2025-07-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harena', '0005_institution_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestViewerInviteToken',
        ),
    ]
